export const state = {
  rss: [],
  models: [],
  ttsAudioAssets: [],
  ttsVoices: [],
  prompts: [],
  schedules: [],
  reports: [],
  videoJobs: [],
  runs: [],
  llmCallLogs: [],
  llmCallStats: null,
  authUsers: [],
  auditLogs: [],
  maintenance: null,
  auth: {
    auth_enabled: false,
    authenticated: true,
    username: null,
    role: "admin",
  },
  selectedRunId: null,
  selectedRunEvents: [],
  runEventSource: null,
  videoJobEventSource: null,
  selectedReportId: null,
  selectedReportNews: [],
};
